Update
rafalp/async-caches pull request #10
Opened 2021-03-27 23:27 UTC by Sparkycz

Hey man,

I had implemented a very similar async cache using Redis as storage in a project. 
I applied some changes to merge my implementation with your one. Check it out. Thanks.

- Updated backends - Serialization/Deserialization of values moved to one point
- Updated backends - Implementation of PEP 3119
- Updated backends - Fix cache.get_or_set called with coroutine
- Updated core - Add caching coroutine easily by `__call__()`

2021-04-15 14:27 UTC, Sparkycz commented
@rafalp please, check it out

2021-04-21 19:43 UTC, rafalp commented
Looks good. I'm only wondering if type shouldn't be `Union[Awaitable[Serializable], Serializable]`?

2021-04-23 09:40 UTC, Sparkycz commented
Is `typing` able to check it? I don't know How exact should it be.. However, I think `Awaitable` is enough..

2021-04-27 11:37 UTC, rafalp commented
@Sparkycz mypy checks this. `Awaitable` is a generic type just like `List` or `Dict` are.

2021-05-06 05:59 UTC, Sparkycz commented
OK, updated.

2021-05-08 21:38 UTC, rafalp requested changes

2021-05-08 21:38 UTC, rafalp commented on caches/backends/base.py
> +import json
This line shoud be placed before `from abc`.

2021-05-08 21:38 UTC, rafalp commented on caches/core.py
> +import json
This line should be before `from types`

2021-05-08 21:38 UTC, rafalp commented
Found two more things, but those are small enough. Rest is looking good to me. Thanks!

2021-05-09 12:32 UTC, rafalp approved these changes

2021-05-09 12:32 UTC, merged